# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1
stages:
  - name: Build_docker

  - name: Unit_test
  - name: Test
  - name: Build
  - name: Deploy

  - name: check-taobao-item-price
    if: branch = routine/check-taobao-item-price

  - name: check-xiao-mi-price
    if: branch = routine/check-xiao-mi-price

  - name: Merge

  - name: Cron
    if: type = cron
