# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 10

cache:
  - npm

jobs:
  include:

    - stage: Unit_test
      name: helloworld-tryout
      install:
        - apt-get update
        - apt-get install -qqy curl
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

        - apt-get update
        - apt-get install -qqy yarn
      script:
        - cd helloworld-tryout
        -   npm install -g concurrently
        -   yarn
        -   concurrently -k "live-server --no-browser ." "node index.js"
        - cd ..

    - stage: check-xiao-mi-price
      name: xiao-mi price
      script:
        - cd check-xiao-mi-9-pro-price
        -   yarn
        -   node index.js
        - cd ..

    - stage: check-taobao-item-price
      name: taobao item price
      script:
        - cd taobao-item-monitor
        -   yarn
        -   node index.js
        - cd ..

    - stage: jobsdb-qa-monitor-tryout
      name: jobsdb-qa-monitor-tryout
      script:
        - cd jobsdb-qa-monitor-tryout
        -   yarn
        -   node src/test.js
        -   node src/index.js
        - cd ..

        #Display Firefox
        - export TMP_DIR=$(mktemp -d)
        - cd $TMP_DIR
        -   git clone --depth=1 https://$GITHUB_TOKEN@github.com/louiscklaw/page-change-detect-tryout.git .

        -   git checkout --orphan page-screenshot

        -   rm .git/index
        -   git clean -fdx
        -   cp $TRAVIS_BUILD_DIR/jobsdb-qa-monitor-tryout/jobsdb.png
        -   git add jobsdb.png
        -   git commit -m"update jobsdb screenshot,"
        -   git push -f -u origin page-screenshot

        - cd -

    - stage: Unit_test
      script:
        - cd check-xiao-mi-9-pro-price
        - yarn
        - node index.js
        - cd ..

        - cd taobao-item-monitor
        - yarn
        - node index.js
        - cd ..

        # # jobsdb-qa-monitor-tryout start
        # - cd jobsdb-qa-monitor-tryout
        # - yarn
        # - node index.js
        # - cd ..

        #collect result and save to orphan branch
        - export TMP_DIR=$(mktemp -d)
        - cd $TMP_DIR
        -   git clone --depth=1 https://$GITHUB_TOKEN@github.com/louiscklaw/page-change-detect-tryout.git .

        -   git checkout --orphan page-screenshot

        -   rm .git/index
        -   git clean -fdx

        -   cp $TRAVIS_BUILD_DIR/check-xiao-mi-9-pro-price/*.png .
        -   cp $TRAVIS_BUILD_DIR/taobao-item-monitor/*.png .

        -   git add *.png

        -   git commit -m"update screenshot,"
        -   git push -f -u origin page-screenshot

        - cd -
        # jobsdb-qa-monitor-tryout end














import:
  - credentials.yml
  - ./.travis-merger.yml
  - ./.travis-stages.yml
