# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 10

cache:
  - npm

jobs:
  include:
    - stage: Test
      name: xiao-mi price
      script:
        - cd check-xiao-mi-9-pro-price
        - yarn
        - node index.js
        - cd ..

    - stage: Test
      name: taobao item price
      script:
        - cd taobao-item-monitor
        - yarn
        - node index.js
        - cd ..

import:
  - credentials.yml
  - ./.travis-merger.yml
  - ./.travis-stages.yml
