helloworld_tryout:
  runs-on: ubuntu-latest
  steps:
    - name: helloworld-tryout
      uses: actions/checkout@v2

    - name: helloworld-tryout
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo 'helloworld'
        node --version
        npm -v
        yarn -v
