# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

name: github-actions-helloworld
on: [push, pull_request]

jobs:
  puppeteer_helloworld:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: github-actions-helloworld-tryout
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        cd github-actions-puppeteer-tryout
          sudo npm install -g concurrently live-server
          yarn
          concurrently -k "live-server --no-browser ." "node index.js" || true
        cd ..


  merge:
    needs: [puppeteer_helloworld, taobao_item_monitor, check_xiao_mi_9_pro_price]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: merge branch
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -V
        python3 -m pip install pipenv

        export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
        export PATH="$PATH:$PYTHON_BIN_PATH"

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        pipenv --help



        cd github-build-merger-tryout
          pipenv sync

          pipenv run python3 ./merge.py
        cd ..
