# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

name: github-actions-helloworld

on:
  push:
  schedule:
    - cron:  '0/15 * * * *'

jobs:
  routine-taobao-display-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: routine-taobao-display-card
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          cd taobao-item-monitor
            yarn
            node index.js
          cd ..
