# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

name: test-puppeteer

on: [push]

jobs:
  test-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-puppeteer
          restore-keys: |
            ${{ runner.OS }}-build-puppeteer

      - run: npm i --no-optional --no-audit puppeteer pixelmatch pngjs

      - run: |
          cd helloworld-tryout
            node example-com-test.js
          cd ..

        env:
          PORT: 0
          NODE_ENV: production # prevent watching

      - uses: actions/upload-artifact@master
        with:
          name: screenshot-puppeteer-darwin
          path: screen-capture.png
